### ISSUE TITLE
Permission denied error on Ubuntu when user created a lib folder inside the downloaded folder.

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#17]
I'm trying to install the community edition like this  `cd supertokens && mkdir lib && ./install --path=./lib` but I'm getting this error. 
```
java.io.IOException: Permission denied
        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.base/java.io.File.createNewFile(File.java:1024)
        at io.supertokens.cli.commandHandler.install.InstallHandler.createSupertokensScript(InstallHandler.java:205)
        at io.supertokens.cli.commandHandler.install.InstallHandler.doCommand(InstallHandler.java:86)
        at io.supertokens.cli.commandHandler.CommandHandler.handleCommand(CommandHandler.java:49)
        at io.supertokens.cli.Main.start(Main.java:122)
        at io.supertokens.cli.Main.main(Main.java:70)

error while installing SuperTokens. Please try again
```

**Comment by yowayb** [comment]
Unable to reproduce on `Ubuntu 20.04.3 LTS` with `supertokens` core binary `3.8`

```bash
rushdie@narwhal:~/Desktop/supertokens$ mkdir lib && ./install --path=./lib
Fetching dependency locations...
Downloading (1/25): https://repo1.maven.org/maven2/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar into core
...
Downloading (25/25): https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.10.0/jackson-annotations-2.10.0.jar into cli

Installation failed. Try again with sudo.
rushdie@narwhal:~/Desktop/supertokens$ sudo ./install --path=./lib
Swipe your finger across the fingerprint reader
Fetching dependency locations...
Downloading (1/25): https://repo1.maven.org/maven2/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar into core
...
Downloading (25/25): https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.10.0/jackson-annotations-2.10.0.jar into cli

Successfully installed SuperTokens! You can now delete this directory safely
Run "supertokens --help" to see list of available commands
Please fill in the compulsory fields in the config file located here: ./lib/config.yaml
```

**Comment by rishabhpoddar** [comment]
Probably. Closing this issue now since it does seem to work! Thanks
