### ISSUE TITLE
Possible bug in transactions in passwordless code creation

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#373]
```
16 Feb 2022 12:12:55:203 +0000 | ERROR | pid: aece6a5f-e72a-4045-b5df-fe58ca2b02af | [http-nio-0.0.0.0-8080-exec-4] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:161) | javax.servlet.ServletException: io.supertokens.pluginInterface.exceptions.StorageQueryException: io.supertokens.pluginInterface.exceptions.StorageTransactionLogicException: org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on identification as a pivot, during commit attempt.
  Hint: The transaction might succeed if retried.
	at io.supertokens.webserver.api.passwordless.CreateCodeAPI.doPost(CreateCodeAPI.java:103)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.supertokens.pluginInterface.exceptions.StorageQueryException: io.supertokens.pluginInterface.exceptions.StorageTransactionLogicException: org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on identification as a pivot, during commit attempt.
  Hint: The transaction might succeed if retried.
	at io.supertokens.storage.postgresql.Start.createDeviceWithCode(Start.java:1202)
	at io.supertokens.passwordless.Passwordless.createCode(Passwordless.java:70)
	at io.supertokens.webserver.api.passwordless.CreateCodeAPI.doPost(CreateCodeAPI.java:77)
	... 21 more
Caused by: io.supertokens.pluginInterface.exceptions.StorageTransactionLogicException: org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on identification as a pivot, during commit attempt.
  Hint: The transaction might succeed if retried.
	at io.supertokens.storage.postgresql.queries.PasswordlessQueries.lambda$createDeviceWithCode$0(PasswordlessQueries.java:114)
	at io.supertokens.storage.postgresql.Start.startTransactionHelper(Start.java:212)
	at io.supertokens.storage.postgresql.Start.startTransaction(Start.java:163)
	at io.supertokens.storage.postgresql.queries.PasswordlessQueries.createDeviceWithCode(PasswordlessQueries.java:97)
	at io.supertokens.storage.postgresql.Start.createDeviceWithCode(Start.java:1180)
	... 23 more
Caused by: org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on identification as a pivot, during commit attempt.
  Hint: The transaction might succeed if retried.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2510)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2245)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:829)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:851)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:366)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at io.supertokens.storage.postgresql.queries.PasswordlessQueries.lambda$createDeviceWithCode$0(PasswordlessQueries.java:112)
	... 27 more
```

The reason for this is that in the `startTransaction` we are not catching `StorageTransactionLogicException` exception and checking that for retries, and the function for creating a code threw `StorageTransactionLogicException` exception, so it was passed through to the user.

**Comment by rishabhpoddar** [comment]
The issue still doesn't seem to be resolved. As we are getting an error:
```
19 Feb 2022 11:55:12:440 +0000 | ERROR | pid: bd16e4fe-0697-4852-8a23-4628295e6097 | [http-nio-0.0.0.0-8080-exec-4] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:162) | javax.servlet.ServletException: io.supertokens.pluginInterface.exceptions.StorageQueryException: io.supertokens.pluginInterface.exceptions.StorageTransactionLogicException: org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on conflict out to pivot 55353756, during read.
  Hint: The transaction might succeed if retried.
  Where: SQL statement "SELECT 1 FROM ONLY "public"."passwordless_devices" x WHERE "device_id_hash" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
	at io.supertokens.webserver.api.passwordless.CreateCodeAPI.doPost(CreateCodeAPI.java:103)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.supertokens.pluginInterface.exceptions.StorageQueryException: io.supertokens.pluginInterface.exceptions.StorageTransactionLogicException: org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on conflict out to pivot 55353756, during read.
  Hint: The transaction might succeed if retried.
  Where: SQL statement "SELECT 1 FROM ONLY "public"."passwordless_devices" x WHERE "device_id_hash" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
	at io.supertokens.storage.postgresql.Start.createDeviceWithCode(Start.java:1212)
	at io.supertokens.passwordless.Passwordless.createCode(Passwordless.java:70)
	at io.supertokens.webserver.api.passwordless.CreateCodeAPI.doPost(CreateCodeAPI.java:77)
	... 21 more
Caused by: io.supertokens.pluginInterface.exceptions.StorageTransactionLogicException: org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on conflict out to pivot 55353756, during read.
  Hint: The transaction might succeed if retried.
  Where: SQL statement "SELECT 1 FROM ONLY "public"."passwordless_devices" x WHERE "device_id_hash" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
	at io.supertokens.storage.postgresql.queries.PasswordlessQueries.lambda$createDeviceWithCode$0(PasswordlessQueries.java:114)
	at io.supertokens.storage.postgresql.Start.startTransactionHelper(Start.java:224)
	at io.supertokens.storage.postgresql.Start.startTransaction(Start.java:163)
	at io.supertokens.storage.postgresql.queries.PasswordlessQueries.createDeviceWithCode(PasswordlessQueries.java:97)
	at io.supertokens.storage.postgresql.Start.createDeviceWithCode(Start.java:1192)
	... 23 more
Caused by: org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on conflict out to pivot 55353756, during read.
  Hint: The transaction might succeed if retried.
  Where: SQL statement "SELECT 1 FROM ONLY "public"."passwordless_devices" x WHERE "device_id_hash" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2510)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2245)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at io.supertokens.storage.postgresql.queries.PasswordlessQueries.createCode_Transaction(PasswordlessQueries.java:187)
	at io.supertokens.storage.postgresql.queries.PasswordlessQueries.lambda$createDeviceWithCode$0(PasswordlessQueries.java:111)
	... 27 more
```

**Comment by rishabhpoddar** [comment]
Closing this since we have figured out the issue
