### ISSUE TITLE
Unit tests fail to execute due to `coroutine 'Supertokens.send_telemetry' was never awaited`

### ISSUE THREAD

**Issue by Acelxrd95** [supertokens/supertokens-core#421]
## 🐛 Bug Report

Unit test fails to execute useing FastAPI's TestClient() function with unittest library due to the error:

`sys:1: RuntimeWarning: coroutine 'Supertokens.send_telemetry' was never awaited`

## Useful informations
This is the code I wrote using unittest

```py
import unittest

from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


class LoginTests(unittest.TestCase):
    correct_mail = "johndoe@gmail.com"
    correct_password = "testPass123"
    false_mail = "wrong@gmail.com"
    false_password = "123456"

    def test_create_user(self):
        response = client.post(
            "/auth/signup", json={
                "formFields": [
                    {
                        "id"   : "email",
                        "value": self.correct_mail
                        },
                    {
                        "id"   : "password",
                        "value": self.correct_password,
                        }
                    ]
                }
            )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json()["status"], "OK")
```

Here is the terminal output upon running the test

```
Launching unittests with arguments python -m unittest tests.LoginTests.test_create_user in C:\Users\ymg59\Documents\Programming\Websecurity-CW\tests

Traceback (most recent call last):
  File "C:\Users\ymg59\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\213.7172.26\plugins\python\helpers\pycharm\_jb_unittest_runner.py", line 35, in <module>
    sys.exit(main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING))
  File "C:\Users\ymg59\AppData\Local\Programs\Python\Python310\lib\unittest\main.py", line 100, in __init__
    self.parseArgs(argv)
  File "C:\Users\ymg59\AppData\Local\Programs\Python\Python310\lib\unittest\main.py", line 147, in parseArgs
    self.createTests()
  File "C:\Users\ymg59\AppData\Local\Programs\Python\Python310\lib\unittest\main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "C:\Users\ymg59\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\ymg59\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\ymg59\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\ymg59\Documents\Programming\Websecurity-CW\tests\tests.py", line 5, in <module>
    from app.main import app
  File "C:\Users\ymg59\Documents\Programming\Websecurity-CW\app\main.py", line 15, in <module>
    init(
  File "C:\Users\ymg59\AppData\Local\pypoetry\Cache\virtualenvs\websecurity-cw-dIKZLFsj-py3.10\lib\site-packages\supertokens_python\__init__.py", line 33, in init
    return Supertokens.init(app_info, framework,
  File "C:\Users\ymg59\AppData\Local\pypoetry\Cache\virtualenvs\websecurity-cw-dIKZLFsj-py3.10\lib\site-packages\supertokens_python\supertokens.py", line 222, in init
    Supertokens.__instance = Supertokens(
  File "C:\Users\ymg59\AppData\Local\pypoetry\Cache\virtualenvs\websecurity-cw-dIKZLFsj-py3.10\lib\site-packages\supertokens_python\supertokens.py", line 189, in __init__
    asyncio.create_task(self.send_telemetry())
  File "C:\Users\ymg59\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 336, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'Supertokens.send_telemetry' was never awaited
```

**Comment by rishabhpoddar** [comment]
This has been fixed and released in v0.6.4
