### ISSUE TITLE
Running supertokens stop gives an error

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#48]
```
java.io.IOException: Cannot run program "kill": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at io.supertokens.cli.commandHandler.stop.StopHandler.stopProcess(StopHandler.java:90)
	at io.supertokens.cli.commandHandler.stop.StopHandler.doCommand(StopHandler.java:52)
	at io.supertokens.cli.commandHandler.CommandHandler.handleCommand(CommandHandler.java:31)
	at io.supertokens.cli.Main.start(Main.java:101)
	at io.supertokens.cli.Main.main(Main.java:49)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 6 more

Could not stop SuperTokens instances. Please try again
```

This happens inside the docker container, however, it may also be happening without docker.

**Comment by loingo95** [comment]
I meet the same issue even when running as supertokens user. Commands and output

```
root@0815336b70ad:/# su supertokens

supertokens@0815336b70ad:/$ supertokens start
Loading supertokens config.
Completed config.yaml loading.
Loading storage layer.
Using in memory storage.
Loading supertokens version.yaml file.
...
Started SuperTokens on 0.0.0.0:3567 with PID: 36

supertokens@0815336b70ad:/$ supertokens stop
java.io.IOException: Cannot run program "kill": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at io.supertokens.cli.commandHandler.stop.StopHandler.stopProcess(StopHandler.java:90)
	at io.supertokens.cli.commandHandler.stop.StopHandler.doCommand(StopHandler.java:52)
	at io.supertokens.cli.commandHandler.CommandHandler.handleCommand(CommandHandler.java:31)
	at io.supertokens.cli.Main.start(Main.java:103)
	at io.supertokens.cli.Main.main(Main.java:50)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 6 more
