### ISSUE TITLE
Supertokens does not start when no access to internet because of telemetry

### ISSUE THREAD

**Issue by albehrens** [supertokens/supertokens-core#559]
## 🐛 Bug Report

We run the Supertokens service in a private subnet without access to the internet. When we start the process it crashes, because it cannot send telemetric data. This is easy to fix by disabling telemetry. But we believe that Supertokens should not crash when telemetry is enabled and there is no access to the internet.

## Useful informations

(Write what happened. Add screenshots, stacktraces, videos, anything that can help)

**Comment by rishabhpoddar** [comment]
Hey @albehrens i agree. This is a bug indeed - we always intended for the telemetry job to not affect he actual running of the core.

Do you have a stack trace for this error? If you started the core in daemon mode, then you can see the error log file generated by the core.

Thanks

**Comment by albehrens** [comment]
We are running Supertokens on AWS. Those are the Cloudwatch logs from the error. I hope this is helpful to you?!

```
17 Jan 2023 20:25:27:830 +0000 | ERROR | pid: d56d44ee-94e3-4ba9-9374-ad19bed7acf4 | [pool-1-thread-1] thread | io.supertokens.cronjobs.CronTask.run(CronTask.java:47) | java.net.SocketTimeoutException: Connect timed out

2023-01-17T21:25:27.830+01:00	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)

2023-01-17T21:25:27.830+01:00	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)

2023-01-17T21:25:27.830+01:00	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)

2023-01-17T21:25:27.830+01:00	at java.base/java.net.Socket.connect(Socket.java:648)

2023-01-17T21:25:27.830+01:00	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1375)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1350)

2023-01-17T21:25:27.830+01:00	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)

2023-01-17T21:25:27.830+01:00	at io.supertokens.httpRequest.HttpRequest.sendJsonRequest(HttpRequest.java:143)

2023-01-17T21:25:27.830+01:00	at io.supertokens.httpRequest.HttpRequest.sendJsonPOSTRequest(HttpRequest.java:185)

2023-01-17T21:25:27.830+01:00	at io.supertokens.cronjobs.telemetry.Telemetry.doTask(Telemetry.java:83)

2023-01-17T21:25:27.830+01:00	at io.supertokens.cronjobs.CronTask.run(CronTask.java:44)

2023-01-17T21:25:27.830+01:00	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

2023-01-17T21:25:27.830+01:00	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)

2023-01-17T21:25:27.830+01:00	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)

2023-01-17T21:25:27.830+01:00	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

2023-01-17T21:25:27.830+01:00	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

2023-01-17T21:25:27.830+01:00	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by rishabhpoddar** [comment]
Hey @albehrens we cannot replicate the crashing of the core - we do get the error stack, but it doesn't really stop the core and things function normally. 

Is the issue replicable on your end? And can you provide me all the core logs please?

**Comment by rishabhpoddar** [comment]
Closing this issue due to inactivity and cause we can't reproduce it. But please feel free to reopen it with more info.
