### ISSUE TITLE
/recipe/session/refresh endpoint is breaking for supertokens core

### ISSUE THREAD

**Issue by NabeelAtCF** [supertokens/supertokens-core#579]
## 🐛 Bug Report

[Context] we are using the self-hosted version of `supertokens-core` in kubernetes (with the help of helmchart mentioned here https://github.com/supertokens/supertokens-docker-postgresql/tree/master/helm-chart ) with `thirdpartypasswordless` recipe , in `golang` backend sdk (with `gin` framework)
now, in the refresh session flow, the call to core at `/recipe/session/refresh` from the golang-sdk is breaking 

And when i tried manually calling `supertokens-core` via  cURL with:
`curl --request POST 'http://supertokens:3567/recipe/session/refresh' --header 'api-key: <api-key here>' --header 'rid: session' --header 'content-type: application/json; charset=utf-8' --header 'cdi-version: 2.14' --data-raw '{"refreshToken": "<refresh token here>", "enableAntiCsrf": false}'`

the response returned by core is 
`{"status":"UNAUTHORISED","message":"java.lang.IllegalArgumentException: Illegal base64 character 25"}`

PS: when I tried the refresh flow locally, with docker image of supertokens-core ran locally, the same call to `/recipe/session/refresh` via golang-sdk is getting response `OK` (with the same sdk version of supertokens in golang) 

## Useful informations

registry version of supertoken-core used is 3.14 at both the places

local OS is `macOS Monterey `

and kubernetes OS is :
```
"Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
```

(Write what happened. Add screenshots, stacktraces, videos, anything that can help)
error logs in pod are : 

```
10 Mar 2023 14:56:19:509 +0000 | DEBUG | pid: c19e204e-4737-44e6-a236-5c14f2e5901c | [http-nio-0.0.0.0-3567-exec-5] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:157) | API called: /recipe/session/refresh. Method: POST. Version: 2.14

10 Mar 2023 14:56:19:509 +0000 | DEBUG | pid: c19e204e-4737-44e6-a236-5c14f2e5901c | [http-nio-0.0.0.0-3567-exec-5] thread | io.supertokens.webserver.api.session.RefreshSessionAPI.doPost(RefreshSessionAPI.java:70) | io.supertokens.exceptions.UnauthorisedException: java.lang.IllegalArgumentException: Illegal base64 character 25
	at io.supertokens.session.refreshToken.RefreshToken.getInfoFromRefreshToken(RefreshToken.java:64)
	at io.supertokens.session.Session.refreshSession(Session.java:300)
	at io.supertokens.webserver.api.session.RefreshSessionAPI.doPost(RefreshSessionAPI.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:162)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 25
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:791)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:567)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:590)
	at io.supertokens.utils.Utils.decrypt(Utils.java:185)
	at io.supertokens.session.refreshToken.RefreshToken.getInfoFromRefreshToken(RefreshToken.java:54)
	... 23 more

10 Mar 2023 14:56:19:510 +0000 | DEBUG | pid: c19e204e-4737-44e6-a236-5c14f2e5901c | [http-nio-0.0.0.0-3567-exec-5] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:182) | API ended: /recipe/session/refresh. Method: POS
```T

**Comment by rishabhpoddar** [comment]
Would it be possible for you to SSH into one of the pods and try refreshing from inside the docker container itself?

**Comment by NabeelAtCF** [comment]
yes, for that I'll be sitting with internal devop person, will update here about the outcome

**Comment by rishabhpoddar** [comment]
This does not seem to be an issue with supertokens: https://discord.com/channels/603466164219281420/1083755020161388676/1085158073989087253
