### ISSUE TITLE
Binary installation fails on windows

### ISSUE THREAD

**Issue by hernanrz** [supertokens/supertokens-core#681]
## 🐛 Bug Report

When running ./install.bat on windows, the following error occurs after a few seconds:

```
PS C:\Users\Usuario\Downloads\supertokens\supertokens> ./install.bat
Fetching dependency locations...
Downloading (1/35): https://repo1.maven.org/maven2/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar into core
Quitting installation because of an error
java.io.IOException: No internet connection
        at io.supertokens.downloader.Main.downloadFile(Main.java:130)
        at io.supertokens.downloader.Main.start(Main.java:95)
        at io.supertokens.downloader.Main.main(Main.java:38)

What caused the crash: Error while downloading jar dependencies. Is your internet connection working?
Installation failed. Please try again

```

I've tried this on three different computers with: Windows 11, Windows 10, and Windows Server 2012 every time the same error, I can copy the URL and paste in my browser and it works OK, so internet connection is not the real problem. Any help would be appreciated.

I also installed OpenJDK but that didn't make a difference

**Comment by hernanrz** [comment]
After inspecting the source code, I found that the downloader connects to `www.google.com` on port `80`, to check if internet is available, we found that our router was blocking outgoing connections to port 80, changing the router config fixed this, sorry for the false alarm!
