### ISSUE TITLE
500 error during passwordless sign up

### ISSUE THREAD

**Issue by porcellus** [supertokens/supertokens-core#828]
## 🐛 Bug Report

We get a 500 error during passwordless sign up using the below setup:

Reproduction:
- Sign up with emailA using the emailpassword recipe
- Sign up with a phone number using the passwordless recipe
- Link the two users above (emailA + an unrelated phone number)
- Sign up with emailA using the passwordless recipe

The last call results in a 500 error.

## Useful informations

Stacktrace from `error.log`:

```
05 Oct 2023 10:25:41:489 +0200 | ERROR | pid: 3c221a9c-e474-4465-b9a8-3e8fc64e7d82 | [http-nio-127.0.0.1-3567-exec-6] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:446) | Tenant(, public, public) | java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "currLM.email" is null
	at io.supertokens.passwordless.Passwordless.consumeCode(Passwordless.java:402)
	at io.supertokens.webserver.api.passwordless.ConsumeCodeAPI.doPost(ConsumeCodeAPI.java:86)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:443)
	at io.supertokens.webserver.PathRouter.service(PathRouter.java:100)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)

05 Oct 2023 10:25:41:492 +0200 | ERROR | pid: 3c221a9c-e474-4465-b9a8-3e8fc64e7d82 | [http-nio-127.0.0.1-3567-exec-6] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:446) | Tenant(, public, public) | API threw an exception: POST /public/recipe/signinup/code/consume
```

**Comment by rishabhpoddar** [comment]
This has been fixed in core version >= 7.0.2
