### ISSUE TITLE
Getting Connection reset by peer error

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#83]
In the `multipleParallelTransactionTest`, if we do not add the `while(true)` loop in the `ParallelTransactions` class, we get the following error:
```
java.net.SocketException: Connection reset by peer (connect failed)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1337)
	at io.supertokens.test.httpRequest.HttpRequest.sendJsonRequest(HttpRequest.java:154)
	at io.supertokens.test.httpRequest.HttpRequest.sendJsonPOSTRequest(HttpRequest.java:198)
	at io.supertokens.test.StorageTest$ParallelTransactions.run(StorageTest.java:578)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

- If we delay the creation of threads by even 1 MS, this error does not get thrown.
- This error seems to be due to an extremely high amount of incoming requests to the Tomcat server, given that the thread pool size is just 10 in development.

**Comment by yowayb** [comment]
Is this actually an issue?  If Tomcat is being overwhelmed, isn't TCP `RST` the correct response?

**Comment by rishabhpoddar** [comment]
Yea. You are right. This isn't an actual issue. Closing it. Thanks
